# Generated by Django 3.1.13 on 2023-09-14 14:06

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_auto_20230911_1030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Special_Students',
            new_name='Section',
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 14, 6, 50, 832362)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 14, 6, 50, 832362)),
        ),
    ]
