# Generated by Django 3.1.13 on 2023-09-15 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20230915_0835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='category_name',
            new_name='section_name',
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 15, 8, 44, 6, 98705)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 15, 8, 44, 6, 98705)),
        ),
    ]
